---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    networks:
      - spring-cloud-network

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_INTERNAL://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    networks:
      - spring-cloud-network

  sonarqube:
    image: sonarqube:9.6.1-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - film-api
      - client-api

    networks:
      - spring-cloud-network

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"

    networks:
      - spring-cloud-network

  postgres-sql:
    image: postgres
    container_name: postgres-docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    networks:
      - spring-cloud-network

  config-server:
    image: config-server
    container_name: config-server
    ports:
      - "8888:8888"

    networks:
      - spring-cloud-network

  eureka-server:
    image: camiloducuara/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network
    depends_on:
      - config-server



  film-api:
    image: camiloducuara/film
    container_name: film-api

    depends_on:
      - zookeeper
      - broker
      - postgres-sql
      - config-server
      - eureka-server

    networks:
      - spring-cloud-network

  client-api:
    image: camiloducuara/client
    container_name: client-api

    ports:
      - "8082:8082"

    depends_on:
      - zookeeper
      - broker
      - postgres-sql
      - config-server
      - eureka-server

    networks:
      - spring-cloud-network

  user-service:
    image: user-service
    container_name: user-service

    ports:
      - "8083"

    depends_on:
      - postgres-sql
      - config-server
      - eureka-server

    networks:
      - spring-cloud-network


  gateway:
    image: gateway
    container_name: gateway
    ports:
      - "9093:9093"

    depends_on:
      - postgres-sql
      - config-server
      - eureka-server
      - film-api
      - client-api
      - user-service

    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
